### ISSUE TITLE
Dichotomous BTL model

### ISSUE THREAD

**Issue by Sdemaeyer2** [jpritikin/pcFactorStan#1]
Hi Joshua,

First of all, a huge thanks for this work you've done. I'm setting my own first steps in Stan and Bayesian modelling and packages like this are a great resource to learn. 

In my research we've focussed on the use of the BTL model for comparative judgement in education. Now I want to implement the same model making use of your package in Stan. I will sketch the basic structure of the data. We had for instance 40 judges comparing short texts written by students. They only had to judge which of both texts met the criteria best. So I guess this resembles the unidimensional model you've described. Judges all had 20 judgements of random composed pairs. 

The data is at comparison level, with following variables:
- `textA` the text presented left side of the screen
- `textB` the text presented right side of the screen
- `textChoosen` the text that 'wins' the comparison
- `judge` the judge that made the decision

Now I'm a bit puzzled how I have to feed this type of data into your framework. I hope this question is not 'too simple' and I hope this is the place where to ask these kind of questions. 

Kind regards,

Sven

**Comment by jpritikin** [comment]
Where can I learn about the BTL model?

Do you plan to estimate a parameter for the judge? Or do you regard all judges as interchangeable?

From the description of your data, it sounds like you only have one item, `textChoosen`. pcFactorStan is designed for data with more than one item. For example, you might have asked judges to compare texts on `grammar`, `originality`, and `cohesion`. Since you only used one item, have you considered [BradleyTerry2](https://cran.r-project.org/web/packages/BradleyTerry2/index.html)?

**Comment by Sdemaeyer2** [comment]
Thx for your the swift response.

A paper that describes CJ in education is for example: [https://journals.sagepub.com/doi/10.1177/0146621617748321](https://journals.sagepub.com/doi/10.1177/0146621617748321) or [https://www.tandfonline.com/doi/abs/10.1080/0969594X.2019.1602027?journalCode=caie20](https://www.tandfonline.com/doi/abs/10.1080/0969594X.2019.1602027?journalCode=caie20)

When reading about pcFactorStan I was charmed by the possibilities it creates. Exactly as you mention: e.g. compare texts on more items like grammar, cohesion, ... That's something I'll be applying in the near future and I will want to compare it with the more holistic approach we use now (presenting judges with a description of text quality and ask judges which of both texts is best according to this description). That's exactly why I would love to implement the more holistic approach (a 1 item situation) in Stan as well. Is the step of estimating the `unidim_alpha` model not the way forward for me here?

Also the idea of identification of diverging judges is something to work on. That can be very relevant in educational assessment situations. If your looking for relevant datasets, we have a large number of datasets of pairwise comparisons (but only with one item so to speak) in different contexts: academic writing; problem solving in maths; coding solutions; moodboards design; ... Always prepared to share!

**Comment by jpritikin** [comment]
> Is the step of estimating the unidim_alpha model not the way forward for me here?

Sure.

> Now I'm a bit puzzled how I have to feed this type of data into your framework.

You could start with 3 columns: textA, textB, and the outcome of the comparison coded as -1 or 1

The identity of the judge is not included in the data because pcFactorStan assumes that judges have no special characteristics.

Just to double-check, you did find the [manual](https://cran.r-project.org/web/packages/pcFactorStan/vignettes/manual.html)?

**Comment by Sdemaeyer2** [comment]
Thx! I think I will be able to proceed from here. 

Found the manual as well.
